### ISSUE TITLE
Freezes when refreshing a long markdown file

### ISSUE THREAD

**Issue by cjmlgrto** [thoughtbot/Markoff#22]
Markoff becomes unresponsive after re-loading/re-rendering any markdown file over 800 words / 4800 characters that has recently been saved.

Note that I'm using a custom CSS template, which you can check out [here in the attachments](https://github.com/thoughtbot/Markoff/files/187479/main.css.zip). I have not yet checked it for the default template.

(Note also that this is probably related to Issue #5.)

**Comment by kaishin** [comment]
Fixed in 0ee3cf3.
