### ISSUE TITLE
App doesn't remember window size across files

### ISSUE THREAD

**Issue by zmwangx** [thoughtbot/Markoff#23]
I'm using Markoff 1.0.0 (51) from MAS on OS X 10.11.4, and every file initially opens in a 480x292 window (that's 960x584 in pixels on the retina screen of my rMBP 15'' with default scaling), which is way too small compared to the font size. Subsequent changes to the window size will be remembered for that one file only, so window resize needs to be done for every single file.

Do you think it's more reasonable to remember window size change across different files (just like how Finder opens new windows according to the size of existing windows, or windows from the last session)?

**Comment by kaishin** [comment]
Markoff _does remember_ the window size per-file. The default size has been too small and has been fixed in https://github.com/thoughtbot/Markoff/commit/792ee9b7b671c64ce19febb8f11483d93aeace90

Also, Finder is not a document-based app, making the comparison is a bit unfair.

Closing for now.
