### ISSUE TITLE
GitHub flavored markdown

### ISSUE THREAD

**Issue by kiliankoe** [thoughtbot/Markoff#3]
Just installed Markoff and am really liking it! Feels slick!

Not sure if at all feasible or a good idea, but it'd be very cool if GitHub flavored markdown were to be supported. Especially features like checklists.

Thanks for considering!

**Comment by kaishin** [comment]
Pretty sure a lot of people will request this feature.

I'd like to stick to using `cmark` as the amrkdown parser, so if you really want your favorite feature to be implemented, [head over here and lobby for it](http://talk.commonmark.org/c/implementation).
