### ISSUE TITLE
Feature Request: Launch from command line

### ISSUE THREAD

**Issue by neckhair** [thoughtbot/Markoff#32]
It would be very nice to launch Markoff directly from the command line (`markoff file.md`).

**Comment by frou** [comment]
This is already possible - put this in your shell's dotfile:

    alias markoff="open -a Markoff"

**Comment by neckhair** [comment]
OK, thanks @frou. That solves it for me. An included "binary" would nice anyway ;-)

**Comment by ajwhite** [comment]
It would be nice if you could specify the file to open. Do we know if this is possible?

**Comment by snoblenet** [comment]
@ajwhite You would do that with `open -a Markoff filename.md`.

This is now in my `init.vim`:
```
augroup Markdown
  autocmd FileType markdown nnoremap <buffer> <leader>m :call OpenMarkoff()<CR>
  autocmd FileType markdown :call OpenMarkoff()<CR>
augroup END

function OpenMarkoff()
  exe '! open -a Markoff '.expand('%')
endfunction
```
What I'd really like is a way to tell Markoff to open at a specific line number (which I would set to be the current line Neovim).

**Comment by stlewis** [comment]
Even better would be a clean way to have Markoff "open" STDOUT
