### ISSUE TITLE
Attached file renders as a blank page

### ISSUE THREAD

**Issue by tebs1200** [thoughtbot/Markoff#6]
The attached file (which appears to be valid markdown as far as I can tell) renders as a completely blank page in Markoff. This same file has no issue being rendered by other systems that use markdown.

[test.txt](https://github.com/thoughtbot/Markoff/files/152580/test.txt)

**Comment by gaomd** [comment]
This file works for me.

**Comment by tebs1200** [comment]
I'm still experiencing an issue. I can open other markdown files just fine (and they render) but not that one. I went through the file adding one line at a time to figure out where the issue was caused.

An issue occurs on line 10 (the one about the API tests) but simply removing that line doesn't solve the problem. I also can't have any paragraphs between two lists. Here's a couple of simpler files - One that works and one that breaks:

[works.txt](https://github.com/thoughtbot/Markoff/files/156080/works.txt)
[breaks.txt](https://github.com/thoughtbot/Markoff/files/156081/breaks.txt)

I hope that helps in some way.

**Comment by mjturner** [comment]
I've found another that displays as blank - see [this file](https://github.com/thoughtbot/Markoff/files/173682/README.md.txt). It renders fine in other Markdown previewers and in Github itself too (see [here](https://github.com/Valloric/YouCompleteMe/blob/master/README.md)).

I'm using version 1.0.0(51), as distributed via the App Store.

**Comment by tebs1200** [comment]
I should probably have mentioned that I'm using the App store distribution too.

**Comment by kaishin** [comment]
Solved in #24.
